name: 创建tag打包并上传docker镜像
# action触发条件
on:
  create:
    tags:
      - '*'  # 仅在创建Tag时触发
# action执行的环境变量
env:
  # docker镜像仓库地址
  REGISTRY: crpi-1arm6bubvql3ps3r.cn-beijing.personal.cr.aliyuncs.com
  # github.repository as <account>/<repo>
  IMAGE_NAME: xfw-release/chaoqian-web

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # 给操作相关权限
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Record start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Image Name
        run: echo "镜像名称：%s" >> $env.IMAGE_NAME
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_USER_PW }}
          port: 22
          script: |
            cd /root/my-docker/x-test
            docker-compose pull
            docker-compose up -d

      - name: Store the commit message
        run: echo "COMMIT_MESSAGE=${{ github.event.commits[0].message }}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Send message to DingTalk
        uses: zcong1993/actions-ding@v4.0.0
        with:
          dingToken: 2b4c30a4f26b9ec01054f0ed687fd60a6bb3a8a493dd0cb3e2ee2898cbe7e0a2
          # https://open.dingtalk.com/document/orgapp/group-messaging-apis-for-interactive-service-windows
          body: |
            {
              "msgtype": "markdown",
              "markdown": {
                  "text": "# ChaoQianWeb更新通知\n\n * 更新的内容: ${{ env.COMMIT_MESSAGE }}",
                  "title": "GithubAction:ChaoQianWeb更新通知"
              }
            }
